version: '3'

services:
  mysqldb:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=monitoramento
      - MYSQL_DATABASE=monitoramento_agua