version: '3'

services:
  apache:
    build:
      dockerfile: Dockerfile
      context: .
    image: mmazoni/php7-apache2-dockerfile
    container_name: php7-apache2
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql:/docker-entrypoint-initdb.d"
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=monitoramento
      - MYSQL_DATABASE=monitoramento_agua

volumes:
  db_data: