name: test

on: [push]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get commit message
        run: |
          echo "GIT_MESSAGE<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: get the version from commit message
        run: |
          MESSAGE_ARRAY=($GIT_MESSAGE)
          echo "VERSION=${MESSAGE_ARRAY[-1]}" >> $GITHUB_ENV
          echo ${MESSAGE_ARRAY[-1]}

      - name: replace version
        run: echo -n $VERSION > VERSION

      - name: setup git config
        run: |
          git config user.name "Mazoni"
          git config user.email "<>"

      - name: merge
        run: |
          git add .
          git commit -m "bump $VERSION"
          git push
          git checkout master
          git merge test_split_string --no-edit
          git push
